version: 1.0
name: run_code_conversion

parameters:
  - id: output_folder
    description: "The path to the folder containing partially converted Python scripts."
    type: "string"

goal: Edit partially converted Python scripts in a user-provided output folder to complete the conversion to MindSpore, and write test scripts.

directories:
  outputs: ${output_folder}
  examples: examples_cohere2

workflow:
  - id: 1
    name: Prompt for output folder path
    actions:
      - type: prompt
        parameter: output_folder
        message: "Please provide the path to the folder containing the partially converted Python scripts."

  - id: 2
    name: Edit partially converted scripts
    actions:
      - Read all files under the provided output folder
      - Treat files in the provided output folder as partially converted MindSpore scripts
      - Continue conversion using diffs
      - Always request human evaluation

  - id: 3
    name: Validate each converted file
    checks:
      - Python AST syntax validation
      - Import resolution check
      - Basic MindSpore API compatibility check
      - Cross-reference with conversion rules

  - id: 4
    name: Review examples as references
    actions:
      - Read all files under `examples_cohere2`
      - Use `cohere2` example as reference for configuration and tests

  - id: 5
    name: Author test scripts
    preconditions:
      - Configuration file exists in the provided output folder
    actions:
      - Write a MindSpore test script for each converted modeling file
      - Use reduced sizes for quick tests:
          batch_size: small
          vocab_size: small
          num_hidden_layers: small
          hidden_size: small
          max_position_embeddings: small

inputs:
  - type: torch_modeling_script
    description: Defines the model architecture (may span multiple files)
  - type: torch_configuration_file
    description: Defines configuration arguments and default values

outputs:
  - type: mindspore_modeling_script
    description: Same functionality as Torch modeling scripts; file count and names align
  - type: mindspore_test_script
    description: Tests that MindSpore and Torch models behave identically on the same inputs

special_handling:
  - condition: MindSpore scripts already exist in the provided output folder
    handling:
      - Treat as partially converted from PyTorch to MindSpore
      - Complete remaining edits using diffs
      - Always ask for human evaluation

references:
  model: cohere2
  files:
    - path: examples_cohere2/configuration_cohere2.py
      role: Model configuration (shared by MindSpore and PyTorch)
    - path: examples_cohere2/modeling_cohere2_torch.py
      role: PyTorch modeling script
    - path: examples_cohere2/modeling_cohere2.py
      role: MindSpore modeling script
    - path: examples_cohere2/test_modeling_cohere2.py
      role: MindSpore test script
