version: 1.0
name: write_test_scripts
parallelizable: false

goal: Write MindSpore test scripts for the converted model, using reduced configurations for quick runs.

dependencies:
  references:
    - examples/configuration_cohere2.py
    - examples/test_modeling_cohere2.py

preconditions:
  - converted_modeling_ready: true

directories:
  outputs: ../output
  examples: ../examples

steps:
  - id: discover_models
    action: list_directory
    path: ../output
  - id: write_tests
    action: generate_mindspore_tests
    for_each: discovered_model_files
    config_overrides:
      batch_size: small
      vocab_size: small
      num_hidden_layers: small
      hidden_size: small
      max_position_embeddings: small
    guidance:
      reference_files:
        - ../examples/configuration_cohere2.py
        - ../examples/test_modeling_cohere2.py
  - id: run_tests
    action: execute_tests
    fail_fast: true

artifacts:
  - type: test_scripts
    location: ../output
  - type: test_results
    location: ../logs/test_results.json
